### ISSUE TITLE
Exception in thread "main" de.tsenger.animamea.pace.PaceException: General Authentication returns: 63 00

### ISSUE THREAD

**Issue by iamtorsten** [tsenger/animamea#1]
Buildfile: /home/torsten/Downloads/animamea-master/animamea/build.xml
download-ivy:
      [get] Getting: http://repo2.maven.org/maven2/org/apache/ivy/ivy/2.1.0-rc2/ivy-2.1.0-rc2.jar
      [get] To: /home/torsten/.ant/lib/ivy.jar
      [get] Not modified - so not downloaded
init-ivy:
resolve:
[ivy:retrieve] :: Ivy 2.1.0-rc2 - 20090704004254 :: http://ant.apache.org/ivy/ ::
[ivy:retrieve] :: loading settings :: url = jar:file:/home/torsten/.ant/lib/ivy.jar!/org/apache/ivy/core/settings/ivysettings.xml
[ivy:retrieve] :: resolving dependencies :: org.apache#hello-ivy;working@dev1
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	found org.bouncycastle#bcprov-jdk15on;1.50 in public
[ivy:retrieve] 	found org.bouncycastle#bcpkix-jdk15on;1.50 in public
[ivy:retrieve] 	found log4j#log4j;1.2.17 in public
[ivy:retrieve] 	found org.apache.openejb#javaee-api;5.0-2 in public
[ivy:retrieve] 	found javax.mail#mail;1.4.3 in public
[ivy:retrieve] 	found javax.activation#activation;1.1 in public
[ivy:retrieve] 	found org.apache.geronimo.specs#geronimo-jms_1.1_spec;1.0 in public
[ivy:retrieve] 	found junit#junit;4.11 in public
[ivy:retrieve] 	found org.hamcrest#hamcrest-core;1.3 in public
[ivy:retrieve] :: resolution report :: resolve 1116ms :: artifacts dl 99ms
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   9   |   0   |   0   |   0   ||   15  |   0   |
	---------------------------------------------------------------------
[ivy:retrieve] :: retrieving :: org.apache#hello-ivy
[ivy:retrieve] 	confs: [default]
[ivy:retrieve] 	0 artifacts copied, 15 already retrieved (0kB/26ms)
compile:
    [javac] Compiling 1 source file to /home/torsten/Downloads/animamea-master/animamea/bin
run:
     [java] 2017-01-24 12:23:44,194 [main] INFO  de.tsenger.animamea.Operator - Entering application.
     [java] 2017-01-24 12:23:44,723 [main] DEBUG de.tsenger.animamea.AmCardHandler - plain C-APDU:
     [java] 00 a4 02 0c 02 01 1c 
     [java] 2017-01-24 12:23:44,745 [main] DEBUG de.tsenger.animamea.AmCardHandler - plain R-APDU:
     [java] 90 00 
     [java] 2017-01-24 12:23:44,745 [main] DEBUG de.tsenger.animamea.AmCardHandler - plain C-APDU:
     [java] 00 b0 00 00 08 
     [java] 2017-01-24 12:23:44,760 [main] DEBUG de.tsenger.animamea.AmCardHandler - plain R-APDU:
     [java] 31 81 c1 30 0d 06 08 04 90 00 
     [java] 2017-01-24 12:23:44,760 [main] DEBUG de.tsenger.animamea.AmCardHandler - plain C-APDU:
     [java] 00 b0 00 00 c4 
     [java] 2017-01-24 12:23:44,778 [main] DEBUG de.tsenger.animamea.AmCardHandler - plain R-APDU:
     [java] 31 81 c1 30 0d 06 08 04 00 7f 00 07 02 02 02 02 
     [java] 01 02 30 12 06 0a 04 00 7f 00 07 02 02 03 02 02 
     [java] 02 01 02 02 01 41 30 12 06 0a 04 00 7f 00 07 02 
     [java] 02 04 02 02 02 01 02 02 01 0d 30 1c 06 09 04 00 
     [java] 7f 00 07 02 02 03 02 30 0c 06 07 04 00 7f 00 07 
     [java] 01 02 02 01 0d 02 01 41 30 2a 06 08 04 00 7f 00 
     [java] 07 02 02 06 16 1e 68 74 74 70 3a 2f 2f 62 73 69 
     [java] 2e 62 75 6e 64 2e 64 65 2f 63 69 66 2f 6e 70 61 
     [java] 2e 78 6d 6c 30 3e 06 08 04 00 7f 00 07 02 02 08 
     [java] 31 32 30 12 06 0a 04 00 7f 00 07 02 02 03 02 02 
     [java] 02 01 02 02 01 45 30 1c 06 09 04 00 7f 00 07 02 
     [java] 02 03 02 30 0c 06 07 04 00 7f 00 07 01 02 02 01 
     [java] 0d 02 01 45 90 00 
     [java] 2017-01-24 12:23:45,047 [main] INFO  de.tsenger.animamea.Operator - EF.CardAccess bytes:
     [java] 31 81 c1 30 0d 06 08 04 00 7f 00 07 02 02 02 02 
     [java] 01 02 30 12 06 0a 04 00 7f 00 07 02 02 03 02 02 
     [java] 02 01 02 02 01 41 30 12 06 0a 04 00 7f 00 07 02 
     [java] 02 04 02 02 02 01 02 02 01 0d 30 1c 06 09 04 00 
     [java] 7f 00 07 02 02 03 02 30 0c 06 07 04 00 7f 00 07 
     [java] 01 02 02 01 0d 02 01 41 30 2a 06 08 04 00 7f 00 
     [java] 07 02 02 06 16 1e 68 74 74 70 3a 2f 2f 62 73 69 
     [java] 2e 62 75 6e 64 2e 64 65 2f 63 69 66 2f 6e 70 61 
     [java] 2e 78 6d 6c 30 3e 06 08 04 00 7f 00 07 02 02 08 
     [java] 31 32 30 12 06 0a 04 00 7f 00 07 02 02 03 02 02 
     [java] 02 01 02 02 01 45 30 1c 06 09 04 00 7f 00 07 02 
     [java] 02 03 02 30 0c 06 07 04 00 7f 00 07 01 02 02 01 
     [java] 0d 02 01 45 
     [java] 2017-01-24 12:23:45,047 [main] INFO  de.tsenger.animamea.Operator - EF.CardAccess decoded
     [java] 2017-01-24 12:23:45,048 [main] DEBUG de.tsenger.animamea.Operator - 
     [java] ------------------
     [java] SecurityInfos object contains
     [java] 1 TerminalAuthenticationInfo objects 
     [java] 1 ChipAuthenticationInfo objects 
     [java] 1 ChipAuthenticationDomainParameterInfo objects 
     [java] 0 ChipAuthenticationPublicKeyInfo objects 
     [java] 1 PaceInfo objects 
     [java] 0 PaceDomainParameterInfo objects 
     [java] 1 CardInfoLocator objects 
     [java] 1 PrivilegedTerminalInfo objects
     [java] ------------------
     [java] TerminalAuthenticationInfo
     [java] 	OID: 0.4.0.127.0.7.2.2.2
     [java] 	Version: 2
     [java] ChipAuthenticationInfo 
     [java] 	OID: 0.4.0.127.0.7.2.2.3.2.2
     [java] 	Version: 2
     [java] 	KeyId 65
     [java] ChipAuthenticationDomainParameterInfo 
     [java] 	OID: 0.4.0.127.0.7.2.2.3.2
     [java] 	DomainParameter: 
     [java] 		0.4.0.127.0.7.1.2
     [java] 		13
     [java] 	KeyId 65
     [java] PaceInfo
     [java] 	OID: 0.4.0.127.0.7.2.2.4.2.2
     [java] 	Version: 2
     [java] 	ParameterId: 13
     [java] CardInfoLocator 
     [java] 	OID: 0.4.0.127.0.7.2.2.6
     [java] 	URL: http://bsi.bund.de/cif/npa.xml
     [java] PrivilegedTerminalInfo
     [java] 	OID: 0.4.0.127.0.7.2.2.8
     [java] 	SecurityInfos: ------------------
     [java] SecurityInfos object contains
     [java] 0 TerminalAuthenticationInfo objects 
     [java] 1 ChipAuthenticationInfo objects 
     [java] 1 ChipAuthenticationDomainParameterInfo objects 
     [java] 0 ChipAuthenticationPublicKeyInfo objects 
     [java] 0 PaceInfo objects 
     [java] 0 PaceDomainParameterInfo objects 
     [java] 0 CardInfoLocator objects 
     [java] 0 PrivilegedTerminalInfo objects
     [java] ------------------
     [java] ChipAuthenticationInfo 
     [java] 	OID: 0.4.0.127.0.7.2.2.3.2.2
     [java] 	Version: 2
     [java] 	KeyId 69
     [java] ChipAuthenticationDomainParameterInfo 
     [java] 	OID: 0.4.0.127.0.7.2.2.3.2
     [java] 	DomainParameter: 
     [java] 		0.4.0.127.0.7.1.2
     [java] 		13
     [java] 	KeyId 69
     [java] 2017-01-24 12:23:45,099 [main] INFO  de.tsenger.animamea.pace.PaceOperator - K from password 120684 is: 31 32 30 36 38 34 
     [java] 2017-01-24 12:23:45,421 [main] DEBUG de.tsenger.animamea.pace.PaceECDH - Point G:
     [java] 04 8b d2 ae b9 cb 7e 57 cb 2c 4b 48 2f fc 81 b7 
     [java] af b9 de 27 e1 e3 bd 23 c2 3a 44 53 bd 9a ce 32 
     [java] 62 54 7e f8 35 c3 da c4 fd 97 f8 46 1a 14 61 1d 
     [java] c9 c2 77 45 13 2d ed 8e 54 5c 1d 54 c7 2f 04 69 
     [java] 97 
     [java] 2017-01-24 12:23:45,755 [main] DEBUG de.tsenger.animamea.AmCardHandler - plain C-APDU:
     [java] 00 22 c1 a4 24 80 0a 04 00 7f 00 07 02 02 04 02 
     [java] 02 83 01 03 7f 4c 12 06 09 04 00 7f 00 07 03 01 
     [java] 02 02 53 05 3f ff ff ff f7 
     [java] 2017-01-24 12:23:45,802 [main] DEBUG de.tsenger.animamea.AmCardHandler - plain R-APDU:
     [java] 90 00 
     [java] 2017-01-24 12:23:45,802 [main] DEBUG de.tsenger.animamea.AmCardHandler - plain C-APDU:
     [java] 10 86 00 00 02 7c 00 ff 
     [java] 2017-01-24 12:23:45,848 [main] DEBUG de.tsenger.animamea.AmCardHandler - plain R-APDU:
     [java] 7c 12 80 10 60 65 aa 4f 6e 94 0e b7 23 1f 83 65 
     [java] 3d be 09 41 90 00 
     [java] 2017-01-24 12:23:45,851 [main] DEBUG de.tsenger.animamea.pace.PaceOperator - encrypted nonce z: 60 65 aa 4f 6e 94 0e b7 23 1f 83 65 3d be 09 41 
     [java] 2017-01-24 12:23:45,857 [main] DEBUG de.tsenger.animamea.pace.PaceOperator - derivatedPassword K_pi: 7c d9 46 49 20 d1 43 6b b1 b4 9a d0 97 f4 e2 5f 
     [java] 2017-01-24 12:23:45,863 [main] DEBUG de.tsenger.animamea.pace.PaceOperator - decrypted nonce s: c3 88 bd 61 91 6b d8 77 95 75 b1 7a 4a d1 f9 c2 
     [java] 2017-01-24 12:23:45,863 [main] DEBUG de.tsenger.animamea.pace.PaceECDH - PCD private key(x1):
     [java] 99 10 53 09 a4 b6 c6 e0 9a 3a f1 a4 ce 8b 66 97 
     [java] 8a c7 94 27 3e 43 19 d3 33 c7 47 24 78 25 21 49 
     [java] 2017-01-24 12:23:45,959 [main] DEBUG de.tsenger.animamea.pace.PaceECDH - PCD public key(X1):
     [java] 04 8d ec 31 ae 88 da 82 ac 52 97 1a cb f5 f8 63 
     [java] 38 37 9b df 97 53 70 76 7c a9 1d ed f3 a5 83 3e 
     [java] 4f 93 fb 26 34 34 6e 63 77 de 9b f4 68 05 d2 0b 
     [java] 54 93 01 4f c9 e9 0a cd 26 33 c8 ea b9 5a bb 1b 
     [java] d4 
     [java] 2017-01-24 12:23:45,959 [main] DEBUG de.tsenger.animamea.AmCardHandler - plain C-APDU:
     [java] 10 86 00 00 45 7c 43 81 41 04 8d ec 31 ae 88 da 
     [java] 82 ac 52 97 1a cb f5 f8 63 38 37 9b df 97 53 70 
     [java] 76 7c a9 1d ed f3 a5 83 3e 4f 93 fb 26 34 34 6e 
     [java] 63 77 de 9b f4 68 05 d2 0b 54 93 01 4f c9 e9 0a 
     [java] cd 26 33 c8 ea b9 5a bb 1b d4 ff 
     [java] 2017-01-24 12:23:46,208 [main] DEBUG de.tsenger.animamea.AmCardHandler - plain R-APDU:
     [java] 7c 43 82 41 04 a2 f1 0d ac 39 26 11 df 84 77 21 
     [java] f7 bb 48 b2 34 d6 6d 88 c3 eb 65 a8 32 e7 40 5d 
     [java] 3a d0 f8 82 ba 99 49 b7 e2 df d5 c8 3c 77 30 b2 
     [java] 55 6a e9 d9 06 b9 be ea 5d d8 d6 9b 4b 21 4c a4 
     [java] 42 f9 e9 5f 46 90 00 
     [java] 2017-01-24 12:23:46,256 [main] DEBUG de.tsenger.animamea.pace.PaceECDH - Shared Secret (P bzw. H):
     [java] 04 74 5b 07 2e 9f c4 fd e9 0a 1a 3d 64 1c 32 78 
     [java] 09 67 b1 8f 45 81 06 e7 1c d7 3e 32 37 77 63 40 
     [java] ba 87 22 37 f7 7e 94 61 59 c5 fe 16 6f 8f bf 0c 
     [java] b0 f9 e9 53 86 ea a1 4e 37 a3 13 1e 04 50 7b 37 
     [java] 6f 
     [java] 2017-01-24 12:23:46,295 [main] DEBUG de.tsenger.animamea.pace.PaceECDH - G_strich:
     [java] 04 09 13 46 17 44 29 b8 f9 1e 93 45 fa 40 7b d0 
     [java] b6 d6 5e 84 86 46 a9 d6 1d 42 34 8f 38 05 9e d1 
     [java] da 5f 00 d8 dd 5e 75 dc 18 e1 b4 19 67 39 41 34 
     [java] 5d 16 f1 7c 45 81 af 70 72 03 1c f7 62 db 5b 51 
     [java] a6 
     [java] 2017-01-24 12:23:46,295 [main] DEBUG de.tsenger.animamea.pace.PaceECDH - PCD private key(x2):
     [java] a3 32 84 70 21 7b 94 2b e1 bf 9b 17 a1 cb 74 8f 
     [java] 8a f4 08 bf cb fd 49 e9 c5 72 41 c2 55 9f 07 07 
     [java] 2017-01-24 12:23:46,315 [main] DEBUG de.tsenger.animamea.pace.PaceECDH - PCD public key(X2):
     [java] 04 8a 8d 4b 37 56 13 47 a7 f5 4a c4 3a b3 f2 ad 
     [java] 18 62 69 ef 1d 19 58 95 05 d3 6b 67 97 9c b7 16 
     [java] 81 46 5f 6c 77 f1 1f 3b 08 29 bc d5 a5 a6 34 45 
     [java] 21 8d 01 9f aa 05 fa df 49 24 30 1a 93 53 26 82 
     [java] a6 
     [java] 2017-01-24 12:23:46,315 [main] DEBUG de.tsenger.animamea.AmCardHandler - plain C-APDU:
     [java] 10 86 00 00 45 7c 43 83 41 04 8a 8d 4b 37 56 13 
     [java] 47 a7 f5 4a c4 3a b3 f2 ad 18 62 69 ef 1d 19 58 
     [java] 95 05 d3 6b 67 97 9c b7 16 81 46 5f 6c 77 f1 1f 
     [java] 3b 08 29 bc d5 a5 a6 34 45 21 8d 01 9f aa 05 fa 
     [java] df 49 24 30 1a 93 53 26 82 a6 ff 
     [java] 2017-01-24 12:23:46,488 [main] DEBUG de.tsenger.animamea.AmCardHandler - plain R-APDU:
     [java] 7c 43 84 41 04 80 9c c0 b3 2e b4 38 7b ea 30 cc 
     [java] 78 f0 74 63 4e fe b4 fa 2c 48 90 1c ca 2d 77 45 
     [java] fb cd d9 cc b4 49 f2 a9 2e 89 35 a6 e1 42 aa 39 
     [java] fe fa 41 46 ca 05 6b 46 6f d7 43 5a b6 35 d3 b2 
     [java] 84 7e 06 d1 21 90 00 
     [java] 2017-01-24 12:23:46,492 [main] DEBUG de.tsenger.animamea.pace.PaceOperator - shared secret (K bzw S): 5d 88 c1 ed 1a 77 6a 41 7e 22 13 30 c5 4d 63 99 
     [java] 49 8d 75 1b 76 6c 4e aa 8f 6a a2 8c 20 21 8a 99 
     [java] 2017-01-24 12:23:46,492 [main] DEBUG de.tsenger.animamea.pace.PaceOperator - Kenc: fb ba a7 13 79 d5 c0 cf b8 7f ee 10 c9 ef 89 1d 
     [java] 2017-01-24 12:23:46,492 [main] DEBUG de.tsenger.animamea.pace.PaceOperator - Kmac: ce 1a 4d a4 fc 9c ef 5a 51 48 5a 31 74 57 f9 52 
     [java] 2017-01-24 12:23:46,509 [main] DEBUG de.tsenger.animamea.AmCardHandler - plain C-APDU:
     [java] 00 86 00 00 0c 7c 0a 85 08 1d f9 3c 52 87 51 eb 
     [java] be ff 
     [java] 2017-01-24 12:23:46,546 [main] DEBUG de.tsenger.animamea.AmCardHandler - plain R-APDU:
     [java] 63 00 
     [java] Exception in thread "main" de.tsenger.animamea.pace.PaceException: General Authentication returns: 63 00 
     [java] 	at de.tsenger.animamea.pace.PaceOperator.sendGeneralAuthenticate(PaceOperator.java:434)
     [java] 	at de.tsenger.animamea.pace.PaceOperator.performMutualAuthentication(PaceOperator.java:447)
     [java] 	at de.tsenger.animamea.pace.PaceOperator.performPace(PaceOperator.java:278)
     [java] 	at de.tsenger.animamea.pace.PaceOperator.performPace(PaceOperator.java:220)
     [java] 	at de.tsenger.animamea.Operator.performPACE(Operator.java:198)
     [java] 	at de.tsenger.animamea.Operator.runCompleteProcedure(Operator.java:100)
     [java] 	at de.tsenger.animamea.Operator.main(Operator.java:92)
     [java] Java Result: 1
BUILD SUCCESSFUL
Total time: 8 seconds

**Comment by iamtorsten** [comment]
Additional informations:

OS: Ubuntu 16.04 64 Bit
Card: Official eID test card from BMI - T0101
Card reader: cyber Jack RFID standard
PIN: Changed before using AusweisApp2

**Comment by tsenger** [comment]
try the last commit 41c8268fcd4582223e9981a9cc2d7d2f1718aa8b
There was an minor bug in the calculation of the shared secret, which only accured in very few runs. 
Not sure if it is the reason for your problem, but give it a try.

**Comment by tsenger** [comment]
Please use a card reader without pinpad. Some readers have a built-in filter to avoid performing PACE from host. 
Support for pinpad reader will be maybe added some time.

**Comment by ndr-brt** [comment]
same issue here. I use a card reader without pinpad (cherry tc 1300).
tried on ubuntu 19.04 and windows 10.

with the following settings:
```
	private final String password = "<the can code on the id card>";
	private final int pwRef = 2;
	private final int terminalRef = 0;
```
any advices?

**Comment by tsenger** [comment]
Can you add a log with the APDUs?

**Comment by ndr-brt** [comment]
> Can you add a log with the APDUs?

Here are the APDU commands and responses:

```
pace.PaceOperator - K from password 076190 is: 30 37 36 31 39 30 

pace.PaceOperator - MSE command: 80 0a 04 00 7f 00 07 02 02 04 01 01 83 01 02 
AmCardHandler - plain C-APDU:
00 22 c1 a4 0f 80 0a 04 00 7f 00 07 02 02 04 01 
01 83 01 02 
AmCardHandler - plain R-APDU:
90 00 

pace.PaceOperator - General Authentication 1
AmCardHandler - plain C-APDU:
10 86 00 00 02 7c 00 00 
AmCardHandler - plain R-APDU:
7c 0a 80 08 75 1d 6b 3b 16 6e ac dc 90 00 
pace.PaceOperator - encrypted nonce z: 75 1d 6b 3b 16 6e ac dc 
pace.PaceOperator - derivatedPassword K_pi: 08 16 f1 67 98 79 38 62 cd d0 51 b0 5d 16 d3 d3 
08 16 f1 67 98 79 38 62 
pace.PaceOperator - decrypted nonce s: eb 0d c0 97 df ab 28 97 00 00 00 00 00 00 00 00 

pace.PaceOperator - General Authentication 2
AmCardHandler - plain C-APDU:
10 86 00 00 00 01 08 7c 82 01 04 81 82 01 00 06 
1b fd fe f5 6b 3c d8 53 4d c0 00 72 93 c9 b5 c7 
69 89 38 d4 07 84 91 43 9f 46 3a c0 b7 e5 ee 38 
54 46 7e 40 04 3d 18 4d 05 b6 ed 69 59 94 a6 cd 
81 aa 2d 3e 31 53 74 23 49 a7 08 f8 e3 99 9b ee 
93 57 12 5b cb 01 e3 4d b4 c8 1a 22 ab ff 36 e0 
9d 39 4b 9c d0 e2 10 ca 29 21 dc 87 8f cc ef 82 
19 08 51 6f 4c d7 0a 49 4d c4 3b bb 04 d3 c0 41 
c6 03 60 f9 b5 b6 c5 19 1d e5 79 6b 98 2d 10 40 
33 3a fb 7c 43 7a 8b 41 9d 6f d0 c2 94 36 4f 3e 
0f 98 b3 6b 5e 03 7d 7a 30 4a 05 c6 6d f1 8a c7 
d5 c2 50 09 e4 ce 72 77 de 26 7c 61 33 44 f6 e0 
8e 59 07 15 27 41 2b eb b8 a4 be fd 18 c7 26 f0 
11 98 f9 18 75 b5 bf 8e 3d ad 15 27 26 62 cc e6 
df 90 78 30 b1 27 0e 51 18 45 14 f2 26 c5 b3 c6 
97 92 10 65 89 5c 56 f3 08 a5 35 4c 67 a9 e7 64 
fb 0c c3 09 2f 12 9b 85 0e b0 73 98 14 1a 03 00 
00 
AmCardHandler - plain R-APDU:
7c 82 01 04 82 82 01 00 44 dc 44 cf 1f ec 75 40 
49 6b 96 ca 38 34 59 e3 0a e4 b3 03 47 8b b5 fe 
d2 e6 0e 40 93 de 43 7f a2 99 77 f7 0e e3 1b 67 
30 2a 11 38 72 96 73 68 bb 5a a3 cd 6b ba c8 21 
e8 62 aa bc 4b 48 1d 26 14 99 38 f2 6e 58 d2 06 
15 bb bc 3b e9 b2 cd 8e 1d e5 a1 ef e4 a7 5e 1f 
e5 a2 8e 30 35 6c 05 a0 fe 41 67 8e 31 70 16 56 
9a 31 18 74 b6 1c 7b 94 7e 6c ac dd b5 e7 8a 66 
d3 e1 a1 93 33 c9 59 8d 77 35 50 9e 7a f3 7a a4 
55 59 08 7e d6 03 17 8b 4a 00 e8 16 29 82 3b c5 
4e 26 ea d4 7a ac 01 ce 0c 8c 39 c2 aa db f3 b6 
2f fd ad f4 aa ef e8 d1 55 f5 66 96 db eb 28 a4 
4c 04 f4 58 7c eb 53 7f 59 cc 31 79 41 fe a6 8d 
df 1c 26 f9 93 c1 38 8e 72 2c 35 f2 d4 de 86 21 
1c 3b 32 27 77 9d 29 44 52 bc 67 6d ce d3 24 ec 
00 7c c1 86 20 c2 e8 13 bc 31 bc 94 4f 82 f4 a9 
d9 40 ec df e0 dd d7 d0 90 00 

pace.PaceOperator - General Authentication 3
AmCardHandler - plain C-APDU:
10 86 00 00 00 01 08 7c 82 01 04 83 82 01 00 26 
9b 7d 4f 10 4d 18 1f 61 25 7f 54 f8 02 80 58 39 
89 f8 f7 64 10 33 b9 59 e1 33 91 18 bd 2f 07 81 
72 b4 b0 d0 d2 82 8d 4c 8d 13 a8 2e b0 38 3d 0e 
49 f8 01 9b f4 4e e4 18 92 a7 fc 08 01 fd d9 b4 
50 5b e5 0e 82 f2 3a 11 e2 96 7c 77 08 c0 1d 35 
98 e3 0e 33 c6 7c 02 23 19 61 2d 80 92 5b 21 4e 
dd 6d a2 e1 d3 96 bd 04 aa 7d fc 05 6c 22 d1 20 
bc 22 63 7f c7 a8 ec 5c 81 7c 67 d0 f5 8d ee 2c 
1f 2e ce c0 6d d7 89 57 a2 00 f0 a0 3d 10 cf f5 
35 52 30 5a e6 4e 48 8c 9b 10 59 04 6b d7 f5 46 
68 15 d1 58 e4 e7 75 86 15 0f 9a df 48 55 e6 87 
af bc 4b c1 23 78 79 58 a2 e7 9a f4 33 56 e4 c9 
82 56 4f 07 a3 88 60 7d ad 07 2b 43 77 32 13 ff 
ef c8 96 d2 6f 75 03 e4 0b 38 cc d0 82 7c 02 32 
18 29 d8 e8 0d 29 3e 32 a2 55 4b 3b 02 ee ff fc 
dc 98 3a c1 6e c9 6b ae 41 ef 27 55 f7 95 a4 00 
00 
AmCardHandler - plain R-APDU:
7c 82 01 04 84 82 01 00 70 d3 15 aa 1f 97 77 67 
4d 31 86 0c 33 94 f2 b8 3a 6c a4 34 5f a2 f9 a1 
0d 92 cb ff 0c 39 a4 a6 01 c0 c1 5d 8b 1a 01 46 
84 32 d0 95 1a 40 cb 8f af 1d c6 3c 35 7d 32 38 
15 40 02 b1 ba 22 fd dd d5 a4 ae ad e4 8b 53 76 
0b 70 20 b1 d6 c0 27 b3 b3 6a 79 85 78 18 f0 79 
a4 bc 3c b9 22 de 5b db 15 f8 96 66 70 9f 82 4c 
fe 46 98 bb d3 0a 1a b6 64 cb f7 bd c2 ce 29 3d 
88 4b 18 f7 2a 72 27 f7 2c 61 fd 66 49 5d ed 4f 
ef 94 4b 94 21 11 77 63 8f 81 20 98 36 85 10 db 
76 91 9f 78 96 aa fe 64 75 84 1d ff 66 ff e9 23 
90 3c 9c 45 7c 43 6c 9c 41 5c 2b 5c e5 ac 00 90 
8d 7e f9 3a 2f 5b aa be 41 4e f0 36 16 0e af 22 
e8 41 1f 02 83 dd 62 2e 83 b3 68 41 5f 45 64 27 
6d 95 99 17 59 13 f0 40 1b bc 4b fa 7e b2 42 ca 
d6 56 65 ab 45 72 a3 a4 7d 3e 96 de c5 68 23 6e 
53 b8 07 19 0c 89 62 b1 90 00 
pace.PaceOperator - shared secret (K bzw S): 2e 6b a1 e9 ec 32 f2 e1 aa cb 06 73 13 dc b8 fa 
51 2c 3e 45 f3 46 90 d0 4e 22 88 8f 44 2e c7 ba 
8e 4f c1 ff e6 8c b7 b5 d8 16 fd 4e 11 63 26 72 
9b 8c 76 f7 53 4f c9 17 5f b3 11 88 93 15 f4 37 
80 d0 4e 68 fd 8b 28 77 94 c7 84 e8 0b cd 9d c2 
3f 2f 4d e6 b6 0f e2 24 d0 44 c1 4d ab 53 b5 ac 
f8 b6 48 be 17 5d fd db f6 83 76 c3 3c 5f 73 87 
ae 0b 8a 81 93 63 c7 14 79 39 41 90 78 23 ce 00 
14 f6 05 ad c1 9d 4a 9a 69 8b c0 04 3e 04 59 f0 
36 53 d0 c1 ec d2 f0 74 88 0a b2 07 18 e7 e1 0e 
a8 87 14 8b 4c 09 d4 8a 5a ec ba d0 c6 52 6a 0f 
3a 70 f7 0d 43 62 6c a5 41 0b 5f a7 0e 21 81 45 
ad c0 97 93 80 da 32 0e 7f 4f 43 e6 01 10 4d 84 
f3 de d6 0a 88 53 44 ca 9e d6 c7 18 49 5e 96 26 
cb c2 e3 c9 92 96 2a 5e 0f 36 d8 4a 61 e0 12 c0 
f4 d7 f6 dc 4f a7 17 12 43 18 fd 63 61 25 cf f7 

pace.PaceOperator - Kenc: 5b 3e 0e a4 1a 13 16 b0 f4 52 1c 2a 2c a1 ea 40 
5b 3e 0e a4 1a 13 16 b0 
pace.PaceOperator - Kmac: cb 9b 45 94 1a 3e d6 98 ab 2c cd 0d f7 ec ab ba 
cb 9b 45 94 1a 3e d6 98 

pace.PaceOperator - General Authentication 4
AmCardHandler - plain C-APDU:
00 86 00 00 0c 7c 0a 85 08 5e 40 f5 fe 48 1f 91 
6a 00 
AmCardHandler - plain R-APDU:
63 00 
```

**Comment by tsenger** [comment]
What kind of document do you use? I assume you're it's an ePassport with PACE?
Then it will use 3DES (instead of AES which I tested a lot more then 3DES).
Seems there was an bug in the [AmDESCrypto.java ](animamea/src/de/tsenger/animamea/crypto/AmDESCrypto.java) with the wrong block length. 
```
@Override
	public byte[] decryptBlock(byte[] key, byte[] z) {
		byte[] s = new byte[blockSize];
		KeyParameter encKey = new KeyParameter(key);
		BlockCipher cipher = new DESedeEngine();
		cipher.init(false, encKey);
		cipher.processBlock(z, 0, s, 0);
		return s;
	}
```
This should fix the problem.
